const EventNames = {
  Atbash: 'atbash',
  CipherType: 'cipherType',
  Code: 'code',
  Column: 'column',
  Compute: 'compute',
  Computed: 'computed',
  CountGrams: 'countGrams',
  Crypt: 'crypt',
  KeyPress: 'keyPress',
  KeyCheck: 'checkKey',
  KeyIncrease: 'increaseKey',
  KeyDecrease: 'decreaseKey',
  KeySquareGen: 'KeySquareGen',
  KeySquareMy: 'KeySquareMy',
  KeySquareRandom: 'KeysquareRandom',
  KeySquareStandard: 'KeySquareStandard',
  KeyValue: 'keyValue',
  Keywords: 'keywords',
  KeywordType: 'keywordType',
  KeywordFirst: 'firstKeyword',
  KeywordSecond: 'secondKeyword',
  Matrix: 'matrix',
  OwnAlphabet: 'ownAlphabet',
  OwnOption: 'ownOption',
  OwnValue: 'ownValue',
  Ciphertxt: 'codtxt',
  CiphertextAlphabet: 'ciphertextabc',
  PlaintextAlphabet: 'plaintextabc',
  Plaintxt: 'orgtxt',
  Substitutiontxt: 'subtxt',
  SetAlphabet: 'setAlphabet',
  TableLength: 'tableLength',
  Toggle: 'toggle',
  ToggleAlphabetOptions: 'toggleAlphabetOptions',
  ToggleDisplayOptions: 'toggleDisplayOptions',
  WarningClash: 'warnClash',
  WarningLength: 'warnLength',
};
export default EventNames;

